
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: green502
  jpa:
    hibernate:
      ddl-auto: update # ????? validate ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true